name: todo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1 
  firebase_core: ^3.6.0
  equatable: ^2.0.5
  omni_datetime_picker: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  horizontal_week_calendar: ^0.0.18
  circular_countdown_timer: ^0.2.4
  flutter_native_splash: ^2.4.3
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/onbording/
    - assets/auth/
    - assets/icons/
    

 
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
