// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw7unPspfMSKhCebEIWtTFH9Gmymbf1Hc',
    appId: '1:988456951076:web:2766572b7432268ff8e7b1',
    messagingSenderId: '988456951076',
    projectId: 'todoapp-f7578',
    authDomain: 'todoapp-f7578.firebaseapp.com',
    storageBucket: 'todoapp-f7578.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeK6lQuOLRL48aNhWYGdItuvPHm-GDiF4',
    appId: '1:988456951076:android:6ba0dad2964b0fbef8e7b1',
    messagingSenderId: '651462062553',
    projectId: 'nadatodoapp',
    storageBucket: 'nadatodoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYT3XyxErxbs645k1MyCofLg0vlfhO-k',
    appId: '1:651462062553:ios:656462c765f30a219729c8',
    messagingSenderId: '651462062553',
    projectId: 'nadatodoapp',
    storageBucket: 'nadatodoapp.firebasestorage.app',
    iosBundleId: 'com.mypackage.todonada',
  );
}
