// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw7unPspfMSKhCebEIWtTFH9Gmymbf1Hc',
    appId: '1:988456951076:web:2766572b7432268ff8e7b1',
    messagingSenderId: '988456951076',
    projectId: 'todoapp-f7578',
    authDomain: 'todoapp-f7578.firebaseapp.com',
    storageBucket: 'todoapp-f7578.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA85HtWYB_T6i0wmB_MNDNKqukbulCyxv8',
    appId: '1:988456951076:android:132b74ea65908b88f8e7b1',
    messagingSenderId: '988456951076',
    projectId: 'todoapp-f7578',
    storageBucket: 'todoapp-f7578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEr8lQ5mEP4wBw8rVIb6vFGYaJ_LfiK0',
    appId: '1:988456951076:ios:d83b64170fee5552f8e7b1',
    messagingSenderId: '988456951076',
    projectId: 'todoapp-f7578',
    storageBucket: 'todoapp-f7578.appspot.com',
    iosClientId: '988456951076-ggalmfdmadivhqb74tb4qa657j79l3o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
